apiVersion:  v1
kind:  Pod
metadata:
  name: httpd-nvme
  labels:
    env:  prod
spec:
  containers:
  - name:  httpd-nvme
    image:  httpd
    imagePullPolicy: IfNotPresent
  nodeSelector:
    disktype: nvme
